### ISSUE TITLE
Crash to main menu when using "sort by saturation" in cooking table

### ISSUE THREAD

**Issue by taiyoko** [Midnight145/blightfall-issue-tracker#124]
Blightfall version: 3.1.1-CE

When I go into the cooking table and hit "sort by saturation", it crashes my game back to the main menu, with the following error in logs:

`[17:18:17] [Server thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
java.lang.NoSuchMethodError: squeek.spiceoflife.foodtracker.FoodHistory.hasEverEaten(Lnet/minecraft/item/ItemStack;)Z
	at net.blay09.mods.cookingforblockheads.container.comparator.ComparatorSoL.compare(ComparatorSoL.java:44) ~[ComparatorSoL.class:?]
	at net.blay09.mods.cookingforblockheads.container.comparator.ComparatorSoL.compare(ComparatorSoL.java:12) ~[ComparatorSoL.class:?]
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:356) ~[?:1.8.0_322]
	at java.util.TimSort.sort(TimSort.java:220) ~[?:1.8.0_322]
	at java.util.Arrays.sort(Arrays.java:1512) ~[?:1.8.0_322]
	at java.util.ArrayList.sort(ArrayList.java:1464) ~[?:1.8.0_322]
	at net.blay09.mods.cookingforblockheads.container.ContainerRecipeBook.sortRecipes(ContainerRecipeBook.java:451) ~[ContainerRecipeBook.class:?]
	at net.blay09.mods.cookingforblockheads.network.HandlerSort.onMessage(HandlerSort.java:34) ~[HandlerSort.class:?]
	at net.blay09.mods.cookingforblockheads.network.HandlerSort.onMessage(HandlerSort.java:14) ~[HandlerSort.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [netty-all-4.0.10.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.0.10.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [netty-all-4.0.10.Final.jar:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[17:18:17] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel cookingforblockheads
java.lang.NoSuchMethodError: squeek.spiceoflife.foodtracker.FoodHistory.hasEverEaten(Lnet/minecraft/item/ItemStack;)Z
	at net.blay09.mods.cookingforblockheads.container.comparator.ComparatorSoL.compare(ComparatorSoL.java:44) ~[ComparatorSoL.class:?]
	at net.blay09.mods.cookingforblockheads.container.comparator.ComparatorSoL.compare(ComparatorSoL.java:12) ~[ComparatorSoL.class:?]
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:356) ~[?:1.8.0_322]
	at java.util.TimSort.sort(TimSort.java:220) ~[?:1.8.0_322]
	at java.util.Arrays.sort(Arrays.java:1512) ~[?:1.8.0_322]
	at java.util.ArrayList.sort(ArrayList.java:1464) ~[?:1.8.0_322]
	at net.blay09.mods.cookingforblockheads.container.ContainerRecipeBook.sortRecipes(ContainerRecipeBook.java:451) ~[ContainerRecipeBook.class:?]
	at net.blay09.mods.cookingforblockheads.network.HandlerSort.onMessage(HandlerSort.java:34) ~[HandlerSort.class:?]
	at net.blay09.mods.cookingforblockheads.network.HandlerSort.onMessage(HandlerSort.java:14) ~[HandlerSort.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[netty-all-4.0.10.Final.jar:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]`

**Comment by taiyoko** [comment]
Looks like it might be the same as issue #105 ? Will try the updated CFB file listed there.

**Comment by Midnight145** [comment]
I *believe* that should fix it, but no matter what i'll be fixed in next patch as I'm switching SoL forks either way
