### ISSUE TITLE
Broken textures everywhere

### ISSUE THREAD

**Issue by GrimbleFitz** [Midnight145/blightfall-issue-tracker#79]
Hello!

Just downloaded this pack via Prism Launcher (running in Flatpak on Fedora Linux). My other instances run fine, but this pack has severe texture issues that leave the main menu un-navigable. Seems like the game is running well, it's just a texture issue as best I can tell. My console output only has a looping error message (below):

```
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.io.IOException: Server returned HTTP response code: 403 for URL: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2134067-better-rain-v0-14
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1902)
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92)
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1492)
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1490)
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.security.AccessController.doPrivileged(Native Method)
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784)
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1489)
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.net.URL.openStream(URL.java:1093)
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.wirsbo.main.MainMod.versioncheck(MainMod.java:71)
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_406_MainMod_versioncheck_ClientTickEvent.invoke(.dynamic)
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325)
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587)
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3006)
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
[15:32:29] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
[15:32:29] [Client thread/ERROR]: ########## GL ERROR ##########
[15:32:29] [Client thread/ERROR]: @ Pre render
[15:32:29] [Client thread/ERROR]: 1281: Invalid value
[15:32:29] [Client thread/ERROR]: ########## GL ERROR ##########
[15:32:29] [Client thread/ERROR]: @ Pre render
[15:32:29] [Client thread/ERROR]: 1281: Invalid value
...
...
...
```

Any suggestions? I'm sure it's a simple fix but I can't find any other record of it around the internet.

**Comment by Midnight145** [comment]
If you're on nvidia, switch to nouveau drivers. A few people on Linux have reported an issue with the stock nvidia drivers with main menu textures

**Comment by GrimbleFitz** [comment]
After updating my drivers and rebooting, the issue went away. I didn't need to switch to the nouveau drivers (though I would have tried that if I hadn't met unexpected success.)

I'll note here for future reference that this texture issue was not unique to Blightfall and affected every 1.7.10 modpack I tested, including vanilla Minecraft 1.7.10.

**Comment by Midnight145** [comment]
Good to know, will point others to this issue in the future. Thank you!
